name: Build para ECR

on:
  push:
    branches:
      - main  # O workflow será executado quando houver um push para a branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Defina a região AWS diretamente aqui
      AWS_REGION: 'us-east-2'  # Substitua pela sua região

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Passo 3: Verificação da variável AWS_REGION
      - name: Verify AWS_REGION
        run: |
          echo "AWS_REGION is set to $AWS_REGION"  # Variável de ambiente do sistema

      # Passo 4: Logar no ECR (Elastic Container Registry)
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}  # Usando a variável de ambiente
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Usando o secret da AWS
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Usando o secret da AWS

      # Passo 5: Construir e enviar a imagem Docker para o ECR
      - name: Build and push Docker image
        run: |
          REPOSITORY_URI=043309320203.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/meu-repositorio-docker
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker push $REPOSITORY_URI:$IMAGE_TAG
